/* Additional record code for OpenIPSL.Examples.Controls.PSSE.ES.EXST1 generated by the OpenModelica Compiler OpenModelica 1.13.0. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Complex__desc_added 1
const char* Complex__desc__fields[2] = {"im","re"};
struct record_description Complex__desc = {
  "Complex", /* package_record__X */
  "Complex", /* package.record_X */
  Complex__desc__fields
};

#define OpenIPSL_Electrical_SystemBase__desc_added 1
const char* OpenIPSL_Electrical_SystemBase__desc__fields[2] = {"S_b","fn"};
struct record_description OpenIPSL_Electrical_SystemBase__desc = {
  "OpenIPSL_Electrical_SystemBase", /* package_record__X */
  "OpenIPSL.Electrical.SystemBase", /* package.record_X */
  OpenIPSL_Electrical_SystemBase__desc__fields
};

#define Modelica_SIunits_ComplexPower__desc_added 1
const char* Modelica_SIunits_ComplexPower__desc__fields[2] = {"im","re"};
struct record_description Modelica_SIunits_ComplexPower__desc = {
  "Modelica_SIunits_ComplexPower", /* package_record__X */
  "Modelica.SIunits.ComplexPower", /* package.record_X */
  Modelica_SIunits_ComplexPower__desc__fields
};

#ifdef __cplusplus
}
#endif

