SimType = ['Machines','Exciters','TurbineGovernors','PowerSystemStabilizers','SeriesElement','ShuntElement']
GensExamples = ['GENSAE','GENSAL','GENROU','GENROE']
EsysExamples = ['EXAC2','ESAC2A','ESST4B','URST5T','SEXS','SCRX','EXAC1','EXST1','ESST1A','IEEEX1','ESAC1A','ESDC1A','ESDC2A','IEEET2','ST5B','IEEET1','EXNI']
TGovExamples = ['IEESGO','HYGOV','GGOV','TGOV1']
PsstExamples = ['PSS2A','IEEEST','PSS2B']
