EventType = ['Fault','LoadVariation','ReferenceStep']
ModelClass = ['Machines','Exciters','TurbineGovernors','PowerSystemStabilizers','RenewableSources','ShuntElement','SeriesElement']
MachExamples = ['GENCLS','GENSAL','GENSAE','GENROU','GENROE','CSVGN1']
EsysExamples = ['EXAC2','ESAC2A','ESST4B','URST5T','SEXS','SCRX','EXAC1','EXST1','ESST1A','IEEEX1','ESAC1A','ESDC1A','ESDC2A','IEEET2','ST5B','IEEET1','EXNI','EXAC3','AC7B','AC8B','DC4B','IEEEVC','ST6B','IEEET3','REXSYS']
TGovExamples = ['IEESGO','HYGOV','GGOV1','TGOV1','GAST','IEEEG1','IEEEG2']
PsstExamples = ['PSS2A','IEEEST','PSS2B'] 
RwbsExamples = ['WT4G1','WT4E1','REECBU1','REECCU1'] 
